# Generated by Django 5.0.7 on 2025-11-01 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome/Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('contato_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Contato')),
                ('contato_cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo do Contato')),
                ('contato_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Contato')),
                ('contato_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Contato')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 00000-000', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta')),
                ('pix', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave PIX')),
                ('prazo_entrega_dias', models.IntegerField(default=0, verbose_name='Prazo de Entrega (dias)')),
                ('prazo_pagamento_dias', models.IntegerField(default=0, verbose_name='Prazo de Pagamento (dias)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado')], default='ativo', max_length=10, verbose_name='Status')),
                ('avaliacao', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, help_text='0 = Não avaliado, 1 = Péssimo, 5 = Excelente', verbose_name='Avaliação (1-5)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['cnpj'], name='fornecedore_cnpj_a9fb5e_idx'), models.Index(fields=['status'], name='fornecedore_status_8cb071_idx')],
            },
        ),
    ]
