# Generated by Django 5.0.7 on 2025-11-01 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Atual')),
                ('quantidade_minima', models.IntegerField(default=0, help_text='Quantidade mínima para alerta de reposição', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Mínima')),
                ('quantidade_maxima', models.IntegerField(default=0, help_text='Capacidade máxima de armazenamento', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Máxima')),
                ('localizacao', models.CharField(blank=True, help_text='Ex: Prateleira A3, Galpão 2, etc.', max_length=100, null=True, verbose_name='Localização')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['produto__nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('motivo', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('devolucao', 'Devolução'), ('ajuste', 'Ajuste de Inventário'), ('perda', 'Perda/Avaria'), ('transferencia', 'Transferência')], max_length=20, verbose_name='Motivo')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Movimentação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('quantidade_anterior', models.IntegerField(default=0, verbose_name='Quantidade Anterior')),
                ('quantidade_posterior', models.IntegerField(default=0, verbose_name='Quantidade Posterior')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
