# Generated by Django 5.0.7 on 2025-11-01 19:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=20, unique=True, verbose_name='Número do Pedido')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('data_entrega_prevista', models.DateField(blank=True, null=True, verbose_name='Data de Entrega Prevista')),
                ('data_entrega_realizada', models.DateField(blank=True, null=True, verbose_name='Data de Entrega Realizada')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('em_separacao', 'Em Separação'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=15, verbose_name='Status')),
                ('valor_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Subtotal')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Desconto')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Frete')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('transferencia', 'Transferência Bancária')], max_length=20, verbose_name='Forma de Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_vendidos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço Unitário')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='produtos.produto', verbose_name='Produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero_pedido'], name='vendas_pedi_numero__35ac03_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', '-data_pedido'], name='vendas_pedi_cliente_7d444a_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status'], name='vendas_pedi_status_406326_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['-data_pedido'], name='vendas_pedi_data_pe_51c122_idx'),
        ),
    ]
