# Generated by Django 5.0.7 on 2025-11-01 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fatura', to='vendas.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='financeiro.fatura', verbose_name='Fatura'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['status'], name='financeiro__status_9cb6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['data_vencimento'], name='financeiro__data_ve_5ce5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['fornecedor'], name='financeiro__fornece_1eeb93_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['categoria'], name='financeiro__categor_4def27_idx'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['numero_fatura'], name='financeiro__numero__3ee315_idx'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['status'], name='financeiro__status_29f087_idx'),
        ),
        migrations.AddIndex(
            model_name='fatura',
            index=models.Index(fields=['data_vencimento'], name='financeiro__data_ve_313d90_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['status'], name='financeiro__status_36b422_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['data_vencimento'], name='financeiro__data_ve_9e57f0_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['cliente'], name='financeiro__cliente_3de520_idx'),
        ),
    ]
