# Generated by Django 5.0.7 on 2025-11-01 19:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Juros'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Multa'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Pago'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Juros'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Multa'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='valor_recebido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Recebido'),
        ),
    ]
