# Generated by Django 5.0.7 on 2025-11-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Modificação'),
        ),
    ]
