# Generated by Django 5.0.7 on 2025-12-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_departamento_data_modificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='departamento',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='ramal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ramal'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='sigla',
            field=models.CharField(default='PADRAO', max_length=10, unique=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('comum', 'Comum'), ('gerente', 'Gerente'), ('admin', 'Administrador')], default='comum', max_length=10, verbose_name='Tipo'),
        ),
    ]
