# Generated by Django 5.0.7 on 2025-11-01 19:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='produtos.categoria', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Venda')),
                ('margem_lucro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Margem de Lucro (%)')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('MT', 'Metro'), ('LT', 'Litro'), ('CX', 'Caixa'), ('PC', 'Peça')], default='UN', max_length=2, verbose_name='Unidade de Medida')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Altura (cm)')),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Largura (cm)')),
                ('profundidade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Profundidade (cm)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/%Y/%m/', verbose_name='Imagem')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('descontinuado', 'Descontinuado')], default='ativo', max_length=15, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['codigo'], name='produtos_pr_codigo_0900e1_idx'), models.Index(fields=['status'], name='produtos_pr_status_9ace39_idx'), models.Index(fields=['categoria'], name='produtos_pr_categor_b0e6ca_idx')],
            },
        ),
    ]
